Added ability to set custom menu toggle keybind.
tf2cheater2013/Fedoraware pull request #433
Opened 2022-06-25 16:45 UTC by VOID-Nightmare

Added ability to set Menu Toggle keybind (default still set to 'insert'), including a keybind input in the Misc Menu.

2022-06-25 17:32 UTC, lnx00 requested changes

2022-06-25 17:32 UTC, lnx00 commented on Fedoraware/TeamFortress2/TeamFortress2/Features/Vars.h
> +		inline CVar<int> MenuKey{ VK_INSERT };
You forgot to save/load this in the config (`ConfigManager.cpp`)

2022-06-25 17:48 UTC, lnx00 approved these changes

2022-06-25 19:10 UTC, johnathon-walnut commented
InputKeybind needs to be updated to allow all keys and not allow the menu key other than on the menu key option

2022-06-26 18:49 UTC, lnx00 requested changes

2022-06-26 18:49 UTC, lnx00 commented on Fedoraware/TeamFortress2/TeamFortress2/Features/Menu/Menu.cpp
> +			InputKeybind("Menu key", Vars::Misc::MenuKey); HelpMarker("The key to open the menu");
Change this to `InputKeybind("Menu key", Vars::Misc::MenuKey, false, true); HelpMarker("The key to open the menu");` to allow special keys

2022-06-26 19:11 UTC, lnx00 approved these changes

2022-06-27 00:54 UTC, merged